image:
  file: .gitpod.Dockerfile

tasks:
  - init: composer install
    command: |
      composer create-project --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
      mv ci/* .
      rm -rf ci

  - init: |
      sudo service mysql start
      sudo mysql -e "CREATE USER 'moodle'@'localhost' IDENTIFIED BY 'moodle';"
      sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'moodle'@'localhost';"
    command: mysql_upgrade

  - init: |
      echo "opening moodle"
    command: |
      /usr/sbin/apache2ctl -D FOREGROUND

ports:
  - port: 80
    onOpen: ignore

vscode:
  extensions:
    - moodlerooms.moodle-theme-development
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
